### ISSUE TITLE
メンター 1日目

### ISSUE THREAD

**Issue by naoki0746** [naoki0746/menta#2]
Linux標準教科書（Ver. 3.0.2）にて基礎を学習

・今日学んだこと
基本ソフトウェアはカーネル、ユーザーランドの二つに分けられる。

カーネル
→OSの中核となる部分で、ハードウェアと直接やりとりする最も中心的な機能を受け持つ部分
ユーザランド
→OSが動作するのに必要なカーネル以外の部分

シェル
→対話型のコマンド入力環境

シェルスクリプト
→コマンドの入力を自動化する為のもの

パッケージ
→Linuxに対して追加機能を提供するもの

・わからなかったこと
書いてある事はぼんやりと理解した気になっているが
今いちピンと来ていない。。
実際に手を動かしながら覚えていかないと理解は難しいと思った

・質問
Linuxのインストールの際にハードディスクの中身を消去と書いてあったが
消去せずに使用したい為、その手順について詳細を教えて頂きたいです。

**Comment by RVIRUS0817** [comment]
@naoki0746 
>今日学んだこと

こちら何章まで読みましたか？
コマンド等は自分で打ってみました？？

>・質問
Linuxのインストールの際にハードディスクの中身を消去と書いてあったが
消去せずに使用したい為、その手順について詳細を教えて頂きたいです。

既存のサーバでいらないものを削除するには可能ですが、消去せずに使用するのは基本無理です。

**Comment by naoki0746** [comment]
>こちら何章まで読みましたか？
>コマンド等は自分で打ってみました？？

→
2章まで読みました
コマンドについては、まだLinuxの環境を設定出来ていなかった為、まだ打っておりません、、

>既存のサーバでいらないものを削除するには可能ですが、消去せずに使用するのは基本無理です。
→上記教えて頂いたので、不要なPCを探して環境を整えてコマンドを打って行きたいと思います。
